config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  get '/auth/spotify/callback', to: 'pages#auth'

  resources :playlists
  resources :users
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_many :tracks
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :playlist
end

app/models/user.rb
class User < ActiveRecord::Base
  serialize :spotify_hash
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def auth
    RSpotify.authenticate("74a5a213821741e1ae60ba4f2f0fac61", "2200ab1ce25c42d6b285a171b1aec60a")
    spotify_user = RSpotify::User.new(request.env['omniauth.auth'])

    @user = User.find_or_create_by({ name: spotify_user.id }) do |new_user|
      new_user.spotify_uri = spotify_user.uri
      new_user.spotify_hash = spotify_user.to_hash
    end

    redirect_to playlists_path
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def index
    @playlists = Playlist.all
  end

  def show
    @playlist = Playlist.find params[:id]
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def add

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find params[:id]
    spotify_user = RSpotify::User.new(@user.spotify_hash)
    @spotify_library = spotify_user.saved_tracks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title SpotifyCollab
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/pages/home.haml
= link_to 'Sign in with Spotify', '/auth/spotify'

app/views/playlists/index.html.haml
.container
  .row
    .col-md-12
      - @playlists.each do |playlist|
        = link_to playlist.name, playlist_path(playlist)

app/views/playlists/show.html.haml
.container
  .row
    .col-md-12
      %table.table
        %thead
          %tr
            %th Track
            %th Artist
            %th Album
            %th Duration
            %th Added
        %tbody
          - @playlist.tracks.each do |track|
            %tr
              %td= image_tag track.thumbnail, {width: "100px"}
              %td= track.artists[0]
              %td= track.album
              %td= number_with_precision(track.duration.to_f / 1000 / 60, :precision => 2)
              %td= time_ago_in_words(track.created_at)

app/views/users/show.html.haml
.container
  .row
    .col-md-12
      %table.table
        %thead
          %tr
            %th Track
            %th Artist
            %th Album
            %th Duration
        %tbody
          - @spotify_library.each do |track|
            %tr
              %td= track.name
              %td= track.artists.map {|a| a.name}.join(',')
              %td= track.album.name
              %td= number_with_precision(track.duration_ms.to_f / 1000 / 60, :precision => 2)